// This file will be auto-generated by Supabase CLI or manually updated
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/supabase.ts

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[];

export interface Database {
    public: {
        Tables: {
            users: {
                Row: {
                    id: string;
                    email: string;
                    full_name: string | null;
                    phone: string | null;
                    role: "customer" | "seller" | "admin";
                    avatar_url: string | null;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    email: string;
                    full_name?: string | null;
                    phone?: string | null;
                    role?: "customer" | "seller" | "admin";
                    avatar_url?: string | null;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    email?: string;
                    full_name?: string | null;
                    phone?: string | null;
                    role?: "customer" | "seller" | "admin";
                    avatar_url?: string | null;
                    created_at?: string;
                };
            };
            stores: {
                Row: {
                    id: string;
                    owner_id: string;
                    name: string;
                    slug: string;
                    description: string | null;
                    logo_url: string | null;
                    address: string | null;
                    is_open: boolean;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    owner_id: string;
                    name: string;
                    slug: string;
                    description?: string | null;
                    logo_url?: string | null;
                    address?: string | null;
                    is_open?: boolean;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    owner_id?: string;
                    name?: string;
                    slug?: string;
                    description?: string | null;
                    logo_url?: string | null;
                    address?: string | null;
                    is_open?: boolean;
                    created_at?: string;
                };
            };
            categories: {
                Row: {
                    id: string;
                    name: string;
                    slug: string;
                    icon: string | null;
                };
                Insert: {
                    id?: string;
                    name: string;
                    slug: string;
                    icon?: string | null;
                };
                Update: {
                    id?: string;
                    name?: string;
                    slug?: string;
                    icon?: string | null;
                };
            };
            products: {
                Row: {
                    id: string;
                    store_id: string;
                    category_id: string;
                    name: string;
                    description: string | null;
                    image_url: string | null;
                    stock: number;
                    is_available: boolean;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    store_id: string;
                    category_id: string;
                    name: string;
                    description?: string | null;
                    image_url?: string | null;
                    stock?: number;
                    is_available?: boolean;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    store_id?: string;
                    category_id?: string;
                    name?: string;
                    description?: string | null;
                    image_url?: string | null;
                    stock?: number;
                    is_available?: boolean;
                    created_at?: string;
                };
            };
            product_variants: {
                Row: {
                    id: string;
                    product_id: string;
                    size_name: string;
                    price: number;
                    stock: number;
                };
                Insert: {
                    id?: string;
                    product_id: string;
                    size_name: string;
                    price: number;
                    stock?: number;
                };
                Update: {
                    id?: string;
                    product_id?: string;
                    size_name?: string;
                    price?: number;
                    stock?: number;
                };
            };
            cart_items: {
                Row: {
                    id: string;
                    user_id: string;
                    product_id: string;
                    variant_id: string | null;
                    quantity: number;
                    notes: string | null;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    user_id: string;
                    product_id: string;
                    variant_id?: string | null;
                    quantity?: number;
                    notes?: string | null;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    user_id?: string;
                    product_id?: string;
                    variant_id?: string | null;
                    quantity?: number;
                    notes?: string | null;
                    created_at?: string;
                };
            };
            orders: {
                Row: {
                    id: string;
                    user_id: string;
                    store_id: string;
                    status: "pending" | "confirmed" | "preparing" | "ready" | "delivered" | "cancelled";
                    total_amount: number;
                    delivery_address: string;
                    payment_method: string;
                    payment_status: "unpaid" | "paid" | "refunded";
                    notes: string | null;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    user_id: string;
                    store_id: string;
                    status?: "pending" | "confirmed" | "preparing" | "ready" | "delivered" | "cancelled";
                    total_amount: number;
                    delivery_address: string;
                    payment_method: string;
                    payment_status?: "unpaid" | "paid" | "refunded";
                    notes?: string | null;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    user_id?: string;
                    store_id?: string;
                    status?: "pending" | "confirmed" | "preparing" | "ready" | "delivered" | "cancelled";
                    total_amount?: number;
                    delivery_address?: string;
                    payment_method?: string;
                    payment_status?: "unpaid" | "paid" | "refunded";
                    notes?: string | null;
                    created_at?: string;
                };
            };
            order_items: {
                Row: {
                    id: string;
                    order_id: string;
                    product_id: string;
                    variant_id: string | null;
                    product_name: string;
                    variant_name: string | null;
                    product_price: number;
                    quantity: number;
                    subtotal: number;
                };
                Insert: {
                    id?: string;
                    order_id: string;
                    product_id: string;
                    variant_id?: string | null;
                    product_name: string;
                    variant_name?: string | null;
                    product_price: number;
                    quantity: number;
                    subtotal: number;
                };
                Update: {
                    id?: string;
                    order_id?: string;
                    product_id?: string;
                    variant_id?: string | null;
                    product_name?: string;
                    variant_name?: string | null;
                    product_price?: number;
                    quantity?: number;
                    subtotal?: number;
                };
            };
        };
        Views: Record<string, never>;
        Functions: Record<string, never>;
        Enums: Record<string, never>;
    };
}
